# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 01:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=b'', max_length=20)),
                ('code', models.CharField(default=b'', max_length=20)),
                ('name', models.CharField(default=b'', max_length=100)),
                ('value', models.CharField(default=b'', max_length=2000)),
                ('status', models.IntegerField(default=0)),
                ('create_time', models.IntegerField(default=0)),
                ('update_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=50)),
                ('keycode', models.CharField(default=b'', max_length=50)),
                ('url', models.CharField(default=b'', max_length=300)),
                ('params', models.CharField(default=b'', max_length=300)),
                ('is_menu', models.IntegerField(default=0)),
                ('sort_id', models.IntegerField(default=0)),
                ('icon_class', models.CharField(default=b'', max_length=100)),
                ('style_css', models.CharField(default=b'', max_length=300)),
                ('status', models.IntegerField(default=1)),
                ('level', models.IntegerField(default=0)),
                ('create_time', models.IntegerField(default=0)),
                ('update_time', models.IntegerField(default=0)),
                ('parent_menu', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_menus', to='system.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField(default=0)),
                ('name', models.CharField(default=b'', max_length=50)),
                ('sort_id', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('create_time', models.IntegerField(default=0)),
                ('update_time', models.IntegerField(default=0)),
            ],
        ),
    ]
