# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 01:10
from __future__ import unicode_literals

import accounts.manager
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(default=b'', max_length=100, unique=True)),
                ('email', models.EmailField(default=b'', max_length=100)),
                ('security', models.CharField(default=b'', max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('create_time', models.IntegerField(default=0)),
                ('update_time', models.IntegerField(default=0)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', accounts.manager.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AccountAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.CharField(default=b'', max_length=20)),
                ('realname', models.CharField(default=b'', max_length=100)),
                ('department', models.CharField(default=b'', max_length=100)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='AccountAdminDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=100)),
                ('description', models.CharField(default=b'', max_length=300)),
                ('status', models.IntegerField(default=1)),
                ('create_time', models.IntegerField(default=0)),
                ('update_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AccountAdminRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=100)),
                ('description', models.CharField(default=b'', max_length=300)),
                ('permission', models.CharField(default=b'', max_length=1000)),
                ('status', models.IntegerField(default=1)),
                ('create_time', models.IntegerField(default=0)),
                ('update_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AccountLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default=b'', max_length=100)),
                ('url', models.CharField(default=b'', max_length=1000)),
                ('request', models.TextField()),
                ('response', models.TextField()),
                ('ip_address', models.CharField(default=b'', max_length=100)),
                ('create_time', models.IntegerField(default=0)),
                ('account_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='accountadmin',
            name='role',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin', to='accounts.AccountAdminRole'),
        ),
        migrations.AddField(
            model_name='accountadmin',
            name='user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
