# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SdkKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=200)),
                ('domain', models.CharField(default=b'', max_length=200)),
                ('token', models.CharField(default=b'', max_length=200)),
                ('access_key', models.CharField(default=b'', max_length=100)),
                ('secret_key', models.CharField(default=b'', max_length=100)),
                ('status', models.IntegerField(default=0)),
                ('create_time', models.IntegerField(default=0)),
                ('update_time', models.IntegerField(default=0)),
            ],
        ),
    ]
