# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 01:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=200)),
                ('alias_name', models.CharField(default=b'', max_length=200)),
                ('province', models.CharField(default=b'', max_length=200)),
                ('address', models.CharField(default=b'', max_length=200)),
                ('zipcode', models.CharField(default=b'', max_length=200)),
                ('telephone', models.CharField(default=b'', max_length=200)),
                ('fax', models.CharField(default=b'', max_length=200)),
                ('website', models.CharField(default=b'', max_length=200)),
                ('email', models.CharField(default=b'', max_length=200)),
                ('license', models.CharField(db_index=True, default=b'', max_length=200)),
                ('license_thumb', models.CharField(default=b'', max_length=300)),
                ('logo', models.CharField(default=b'', max_length=300)),
                ('thumb', models.CharField(default=b'', max_length=300)),
                ('legal_name', models.CharField(default=b'', max_length=300)),
                ('legal_thumb', models.CharField(default=b'', max_length=300)),
                ('status', models.IntegerField(default=0)),
                ('examine_id', models.IntegerField(default=0)),
                ('account_id', models.IntegerField(default=0)),
                ('create_time', models.IntegerField(default=0)),
                ('update_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(default=0)),
                ('agency_company_id', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('create_time', models.IntegerField(default=0)),
                ('update_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyExamine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('desciprtion', models.CharField(default=b'', max_length=500)),
                ('create_time', models.IntegerField(default=0)),
                ('update_time', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examine', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_key', models.CharField(default=b'', max_length=64)),
                ('license_key', models.CharField(default=b'', max_length=128)),
                ('communication', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('create_time', models.IntegerField(default=0)),
                ('update_time', models.IntegerField(default=0)),
                ('company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenses', to='customers.Company')),
            ],
        ),
    ]
