# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20160331_0615'),
        ('customers', '0002_auto_20160331_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='brands',
            field=models.ManyToManyField(related_name='companies', through='products.CompanyBrand', to='products.ProductBrand'),
        ),
    ]
