# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_company_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyAgency',
        ),
        migrations.RemoveField(
            model_name='companyexamine',
            name='user',
        ),
        migrations.RemoveField(
            model_name='companylicense',
            name='company',
        ),
        migrations.DeleteModel(
            name='CompanyExamine',
        ),
        migrations.DeleteModel(
            name='CompanyLicense',
        ),
    ]
