# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_company_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='brands',
            field=models.ManyToManyField(related_name='companies', through='products.CategoryCompanyBrand', to='products.ProductBrand'),
        ),
    ]
