# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20160409_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='brands',
        ),
    ]
