# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 02:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0007_delete_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproveLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField()),
                ('action_date', models.DateField()),
                ('action_type', models.IntegerField(choices=[(0, b'\xe8\xaf\x81\xe6\x98\x8e'), (1, b'\xe5\xae\xa1\xe6\xa0\xb8')], default=0)),
                ('approved', models.BooleanField(default=False)),
                ('message', models.CharField(blank=True, default=None, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('source', models.IntegerField(choices=[(0, b'\xe5\xae\x98\xe7\xbd\x91'), (1, b'\xe8\xae\xbe\xe8\xae\xa1\xe5\xb8\x88\xe5\xb9\xb3\xe5\x8f\xb0'), (2, b'\xe7\x94\xb5\xe5\x95\x86\xe5\xb9\xb3\xe5\x8f\xb0')], default=0)),
                ('username', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('password', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('role', models.IntegerField(choices=[(0, b'\xe6\x99\xae\xe9\x80\x9a\xe7\x94\xa8\xe6\x88\xb7'), (1, b'\xe8\xae\xbe\xe8\xae\xa1\xe5\xb8\x88'), (2, b'\xe4\xbe\x9b\xe5\xba\x94\xe5\x95\x86'), (3, b'\xe8\xa3\x85\xe4\xbf\xae\xe5\x85\xac\xe5\x8f\xb8')], default=0)),
                ('active', models.BooleanField(default=True)),
                ('register_date', models.DateField(blank=True, default=None, null=True)),
                ('avatar', models.ImageField(blank=True, default=None, null=True, upload_to=b'avatar/')),
                ('real_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('birth_date', models.DateField(blank=True, default=None, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=200, null=True)),
                ('certified', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('register_no', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('cert_no', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('bank_no', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('business_license', models.FileField(blank=True, default=None, null=True, upload_to=b'business_license/')),
            ],
        ),
        migrations.AddField(
            model_name='approvelog',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approve_logs', to='customers.CustomerAccount'),
        ),
    ]
