# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_auto_20160411_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=b'', max_length=128, unique=True)),
                ('license', models.CharField(default=b'', max_length=64, unique=True)),
                ('app_secret', models.CharField(default=b'', max_length=64, unique=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='customers.CustomerAccount')),
            ],
        ),
    ]
