# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_accountkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvelog',
            name='action_user',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='gender',
            field=models.IntegerField(choices=[(0, b'\xe7\x94\xb7'), (1, b'\xe5\xa5\xb3')], default=0),
        ),
        migrations.AlterField(
            model_name='accountkey',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='key', to='customers.CustomerAccount'),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='register_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
