# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_auto_20160411_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='domain',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='domain_description',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='domain_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
