# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_auto_20160411_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='domain_description',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True),
        ),
    ]
