# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 05:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_auto_20160411_0325'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingApprove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('domain_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('domain_description', models.CharField(blank=True, default=None, max_length=2000, null=True)),
                ('certified', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('register_no', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('cert_no', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('bank_no', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('business_license', models.FileField(blank=True, default=None, null=True, upload_to=b'business_license/')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_approves', to='customers.CustomerAccount')),
            ],
        ),
    ]
