# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 05:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_pendingapprove'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_code', models.CharField(default=b'', max_length=128)),
                ('username', models.CharField(default=b'', max_length=128)),
                ('user_code', models.CharField(default=b'', max_length=32)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other', to='customers.CustomerAccount')),
            ],
        ),
    ]
