# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_auto_20160411_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='email_certified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='phone_certified',
            field=models.BooleanField(default=False),
        ),
    ]
