# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 01:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=200)),
                ('file_name', models.CharField(default=b'', max_length=200)),
                ('extension', models.CharField(default=b'', max_length=10)),
                ('size', models.CharField(default=b'', max_length=10)),
                ('path', models.CharField(default=b'', max_length=300)),
                ('width', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('create_time', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
