# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 03:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default=b'', max_length=200)),
                ('alias_name', models.CharField(default=b'', max_length=200)),
                ('sale_name', models.CharField(default=b'', max_length=300)),
                ('brand', models.CharField(default=b'', max_length=200)),
                ('key_code', models.CharField(default=b'', max_length=50)),
                ('approve_code', models.CharField(default=b'', max_length=100)),
                ('province', models.CharField(default=b'', max_length=200)),
                ('address', models.CharField(default=b'', max_length=200)),
                ('longitude', models.FloatField(default=0)),
                ('latitude', models.FloatField(default=0)),
                ('thumb', models.CharField(default=b'', max_length=200)),
                ('plan_area', models.CharField(default=b'', max_length=200)),
                ('build_area', models.CharField(default=b'', max_length=200)),
                ('plan_house', models.CharField(default=b'', max_length=200)),
                ('green_rate', models.CharField(default=b'', max_length=200)),
                ('cubage_rate', models.CharField(default=b'', max_length=200)),
                ('house', models.CharField(default=b'', max_length=200)),
                ('build_type', models.CharField(default=b'', max_length=500)),
                ('acreage', models.CharField(default=b'', max_length=500)),
                ('aspect', models.CharField(default=b'', max_length=100)),
                ('min_price', models.FloatField(default=0)),
                ('max_price', models.FloatField(default=0)),
                ('min_avg_price', models.FloatField(default=0)),
                ('max_avg_price', models.FloatField(default=0)),
                ('property_age_limit', models.CharField(default=b'', max_length=200)),
                ('property_type', models.CharField(default=b'', max_length=200)),
                ('renovation', models.CharField(default=b'', max_length=200)),
                ('traffic', models.TextField()),
                ('education', models.TextField()),
                ('life', models.TextField()),
                ('environment', models.TextField()),
                ('property_company', models.CharField(default=b'', max_length=200)),
                ('develop_company', models.CharField(default=b'', max_length=200)),
                ('build_date', models.IntegerField(default=0)),
                ('complete_date', models.IntegerField(default=0)),
                ('deliver_date', models.IntegerField(default=0)),
                ('persell', models.CharField(default=b'', max_length=200)),
                ('tags', models.CharField(default=b'', max_length=300)),
                ('account_id', models.IntegerField(default=0)),
                ('license', models.CharField(default=b'', max_length=200)),
                ('create_time', models.IntegerField(default=0)),
                ('update_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=100)),
                ('description', models.CharField(default=b'', max_length=300)),
                ('status', models.IntegerField(default=0)),
                ('create_time', models.IntegerField(default=0)),
                ('update_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAlbumPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.IntegerField(default=0)),
                ('name', models.CharField(default=b'', max_length=200)),
                ('description', models.CharField(default=b'', max_length=300)),
                ('thumb', models.CharField(default=b'', max_length=300)),
                ('create_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyApartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_type', models.CharField(default=b'', max_length=100)),
                ('name', models.CharField(default=b'', max_length=100)),
                ('description', models.CharField(default=b'', max_length=300)),
                ('thumb', models.CharField(default=b'', max_length=300)),
                ('acreage', models.CharField(default=b'', max_length=10)),
                ('aspect', models.CharField(default=b'', max_length=100)),
                ('coordinate', models.CharField(default=b'', max_length=1000)),
                ('height', models.FloatField(default=0)),
                ('sale_house', models.TextField()),
                ('room', models.IntegerField(default=0)),
                ('hall', models.IntegerField(default=0)),
                ('toilet', models.IntegerField(default=0)),
                ('kitchen', models.IntegerField(default=0)),
                ('balcony', models.IntegerField(default=0)),
                ('create_time', models.IntegerField(default=0)),
                ('update_time', models.IntegerField(default=0)),
                ('property', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartments', to='property.Property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=b'', max_length=20)),
                ('profile_data', models.TextField()),
                ('account_id', models.IntegerField(default=0)),
                ('create_time', models.IntegerField(default=0)),
                ('update_time', models.IntegerField(default=0)),
                ('property', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='property.Property')),
            ],
        ),
    ]
