# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='develop_company',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_company',
        ),
        migrations.AddField(
            model_name='property',
            name='develop_manufactor',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='property_manufactor',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
