# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0002_auto_20160328_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='company_id',
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='customers.Company'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.ProductCategory'),
        ),
    ]
