# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0004_auto_20160329_0240'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductCategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Company')),
            ],
        ),
        migrations.AddField(
            model_name='productcategory',
            name='companies',
            field=models.ManyToManyField(through='products.CategoryCompany', to='customers.Company'),
        ),
    ]
