# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20160331_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='products.ProductCategory'),
        ),
    ]
