# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 02:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productbrand_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbrandseries',
            name='brand_id',
        ),
        migrations.AddField(
            model_name='productbrandseries',
            name='brand',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series', to='products.ProductBrand'),
        ),
    ]
