# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20160331_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbrand',
            name='alias_name',
        ),
        migrations.RemoveField(
            model_name='productbrand',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='productbrand',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productbrand',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='productbrand',
            name='status',
        ),
        migrations.RemoveField(
            model_name='productbrand',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='productbrand',
            name='user',
        ),
        migrations.RemoveField(
            model_name='productbrandseries',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='productbrandseries',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productbrandseries',
            name='status',
        ),
        migrations.RemoveField(
            model_name='productbrandseries',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='productbrandseries',
            name='user',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='sort_id',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='status',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='update_time',
        ),
        migrations.AddField(
            model_name='productbrand',
            name='no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productbrandseries',
            name='no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='no',
            field=models.IntegerField(default=0),
        ),
    ]
