# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 03:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20160331_0323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbrandseries',
            name='company',
        ),
    ]
