# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20160331_0323'),
        ('products', '0009_remove_productbrandseries_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='productbrand',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productbrand',
            name='company',
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='companies',
            field=models.ManyToManyField(related_name='categories', through='products.CategoryCompany', to='customers.Company'),
        ),
        migrations.AddField(
            model_name='companybrand',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductBrand'),
        ),
        migrations.AddField(
            model_name='companybrand',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Company'),
        ),
        migrations.AddField(
            model_name='categorybrand',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductBrand'),
        ),
        migrations.AddField(
            model_name='categorybrand',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductCategory'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='brands',
            field=models.ManyToManyField(related_name='categories', through='products.CategoryBrand', to='products.ProductBrand'),
        ),
    ]
