# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productcategoryattribute_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategoryattribute',
            name='is_search',
        ),
        migrations.RemoveField(
            model_name='productcategoryattribute',
            name='type',
        ),
        migrations.AddField(
            model_name='productcategoryattribute',
            name='searchable',
            field=models.BooleanField(default=True),
        ),
    ]
