# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20160404_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategoryattributevalue',
            name='searchable',
            field=models.BooleanField(default=True),
        ),
    ]
