# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productcategoryattributevalue_searchable'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.IntegerField(choices=[(0, b'\xe4\xba\xa7\xe5\x93\x81'), (1, b'\xe6\xa8\xa1\xe5\x9e\x8b')], default=0),
        ),
    ]
