# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 03:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModelFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=200)),
                ('file', models.FileField(upload_to=b'file/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModelPreviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=200)),
                ('file', models.FileField(upload_to=b'preview/')),
            ],
        ),
        migrations.RemoveField(
            model_name='productcommodity',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productcommoditygoods',
            name='commodity',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='chartlet_path',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='model_path',
        ),
        migrations.DeleteModel(
            name='ProductCommodity',
        ),
        migrations.DeleteModel(
            name='ProductCommodityGoods',
        ),
        migrations.AddField(
            model_name='productmodelpreviews',
            name='model',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previews', to='products.ProductModel'),
        ),
        migrations.AddField(
            model_name='productmodelfiles',
            name='model',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='products.ProductModel'),
        ),
    ]
