# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20160405_0340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default=b'', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='norms',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='norms_no',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='technics',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='version_no',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AlterField(
            model_name='productmodelfiles',
            name='model',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='productmodelpreviews',
            name='model',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previews', to='products.Product'),
        ),
        migrations.DeleteModel(
            name='ProductModel',
        ),
    ]
