# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20160405_0607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodelfiles',
            old_name='model',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productmodelpreviews',
            old_name='model',
            new_name='product',
        ),
    ]
