# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20160405_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productbrand',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productbrandseries',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productcategoryattribute',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productcategoryattributevalue',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productmodelfiles',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productmodelpreviews',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
