# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20160406_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodelfiles',
            name='preview',
            field=models.ImageField(default='', upload_to=b'file/preview/'),
            preserve_default=False,
        ),
    ]
