# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_remove_company_brands'),
        ('products', '0022_auto_20160409_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryManufactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Manufactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=200)),
                ('no', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManufactorBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductBrand')),
                ('manufactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Manufactor')),
            ],
        ),
        migrations.RemoveField(
            model_name='categorycompany',
            name='category',
        ),
        migrations.RemoveField(
            model_name='categorycompany',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companybrand',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='companybrand',
            name='company',
        ),
        migrations.RemoveField(
            model_name='product',
            name='company',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='companies',
        ),
        migrations.DeleteModel(
            name='CategoryCompany',
        ),
        migrations.DeleteModel(
            name='CompanyBrand',
        ),
        migrations.AddField(
            model_name='manufactor',
            name='brands',
            field=models.ManyToManyField(related_name='manufactors', through='products.ManufactorBrand', to='products.ProductBrand'),
        ),
        migrations.AddField(
            model_name='categorymanufactor',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductCategory'),
        ),
        migrations.AddField(
            model_name='categorymanufactor',
            name='manufactor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Manufactor'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufactor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.Manufactor'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='manufactors',
            field=models.ManyToManyField(related_name='categories', through='products.CategoryManufactor', to='products.Manufactor'),
        ),
    ]
